name: AUBlissFuse
version: '1.0-SNAPSHOT'
main: site.thatkid.aUBlissFuse.AUBlissFuse
api-version: '1.21'
softdepend: [ProtocolLib]
commands:
  spawnguide:
    description: Spawn your instruction villager
    usage: /spawnguide
  spawnchicken:
    description: Spawns a chicken who just wants seeds or so you think
    usage: /spawnchicken
  spawnirongolem:
    description: Spawns an iron golem who wants riches
    usage: /spawnirongolem
  spawninfuseteleporter:
    description: spawns the tp npc
    usage: /spawninfuseteleporter
  spawn_boss:
    description: spawns boss
    usage: /spawn_boss

  give_mace_key:
    description: Give a mace key item
    usage: /give_mace_key
    permission: blissfuse.give
  give_teleporter:
    description: Give a teleporter block
    usage: /give_teleporter
    permission: blissfuse.give

  addplayer:
    description: adds someone to the mace event list
    usage: /addplayer
    permission: op
  finalplayers:
    description: Lists all players from players.json
    usage: /finalplayers
    permission: op

  pvp:
    description: toggles pvp
    usage: /pvp <on|off|status|toggle>
    permission: op
  tempban:
    description: temperately bans the player
    usage: /tempban <playername> <time><s|m|h|d|w> <reason>
permissions:
  customvillager.spawn:
    default: op
  blissfuse.give:
    default: op
  ability.use:
    description: Allows the player to use abilities.
    default: false



authors: [ ItsMinechook ]
website: thatkid.site
